### ISSUE TITLE
PSI to bar

### ISSUE THREAD

**Issue by malinduta** [trlafleur/Flow-Sensor-Tasmota#4]
Hello!
Just installed water pressure sensor and is working great, as expected.
Is there a way to change the unit to bar? Also to Home Assistant? 
Will install water flow sensor next days.

**Comment by trlafleur** [comment]
The pressure code is in Berry, you could just scale the reading there....

One PSI = 0.0689476 Bar

**Comment by malinduta** [comment]
self.FlowPres_data = [(d*0.0689476)]
@trlafleur is this correct?
It works good on web sensor, but on home assistant something is not good, it always show 0 bar.

**Comment by trlafleur** [comment]
if I remember,... the first function is displayed on the web... 2nd as MQTT
data, these are where you may want to make the changes.....

#- *************************************** -#
  def web_sensor()
    import string
    if !self.FlowPres_data return nil end               # exit if not
initialized
    var msg = string.format("{s}Water Pressure {m}%7.2f PSI{e}",
self.FlowPres_data[0])
    tasmota.web_send_decimal(msg)
  end


#- *************************************** -#
  def json_append()
    if !self.FlowPres_data return nil end
import string
var msg = string.format(",\"WaterPressure\":{\"PSI\":%.f}",
self.FlowPres_data[0])
    tasmota.response_append(msg)
  end

~~ _/) ~~~~ _/) ~~~~ _/) ~~~~ _/) ~~

Tom Lafleur

**Comment by malinduta** [comment]
Thank you!
It worked :)
