### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by malinduta** [trlafleur/Flow-Sensor-Tasmota#5]
Hello,
I would like to use the flow sensor xsns_125_flow_counter.ino, but I do not know how to use it.
I use tasmocompiler when in need for custom firmware. 
I need some help, please.
Thank you.

**Comment by malinduta** [comment]
@trlafleur, any help would be appreciated.
Some small guide lines would be great.

**Comment by trlafleur** [comment]
Later tonight

**Comment by trlafleur** [comment]
1) first you need the ability to compile Tasmota... last time I did
this it was for 12.3.1.1

2) if you use current version of Tasmota, some of the reference on
where to integrate this driver will change...

     but this will provide a reference on about where the changes need
to go. some need to be at the end of structure.

3) changes need to be made in:
include/tasmota_template.h   and in  tasmota/language/en_GB.h

4) suggest yuou start with 12.3.1.1


trl...




/* **************************************************************************************
Changes made to Tasmota base code...
See integration notes...
12.3.1.1

include/tasmota_template.h
(must be at end of structure)



line 208
GPIO_FLOW, GPIO_FLOW_NP, GPIO_FLOW_LED,        // Flow Sensor xsns_125
     //  <---------------  TRL

line 459
D_SENSOR_FLOW "|" D_SENSOR_FLOW "_n|" D_SENSOR_FLOW_LED "|"
     // <---------------  TRL

line 542
#ifdef USE_FLOW
  AGPIO(GPIO_FLOW),                            // Flow xsns_125
     // <---------------  TRL
  AGPIO(GPIO_FLOW_NP),
  AGPIO(GPIO_FLOW_LED),
#endif

tasmota/language/en_GB.h
at line 921
#define D_SENSOR_FLOW          "H2O Flow"
     // <---------------  TRL
#define D_SENSOR_FLOW_N        "H2O Flow N"
#define D_SENSOR_FLOW_LED      "H2O Flow Led"
*/


~~ _/) ~~~~ _/) ~~~~ _/) ~~~~ _/) ~~

Tom Lafleur

**Comment by trlafleur** [comment]
loaded a pre-compiled bin file to Git Hub from my last compile
it most likely has my internal IP address included...

~~ _/) ~~~~ _/) ~~~~ _/) ~~~~ _/) ~~

Tom Lafleur

**Comment by Noschvie** [comment]
Hi Tom,
Why is your solution not included in Tasmota core?

**Comment by malinduta** [comment]
> loaded a pre-compiled bin file to Git Hub from my last compile it most likely has my internal IP address included...

Great, will try it tonight.

**Comment by trlafleur** [comment]
Because I haven’t taken the time to submit it……

**Comment by malinduta** [comment]
Flashed the file you provided.
Set GPIO16 to H2O Flow, but Flow Rate and Flow Pulse Count show zero.
Heartbeat - how should be used? What is used for?

**Comment by trlafleur** [comment]
I re-built code tonight....

did a quick test on an ESP32, as you can see code is working..

I'm sending it a 1hz pulse on GPIO 14
and LED connected on GPIO 32 will change state on each pulse
and GPIO 13 will blink a heartbeat from Tasmota base code...

analog input is on GPIO 36, but to user pressure, you must also load the
Berry code..

I update the code on github

[image: image.png]


[image: image.png]



~~ _/) ~~~~ _/) ~~~~ _/) ~~~~ _/) ~~

Tom Lafleur

**Comment by trlafleur** [comment]
here is a list of commands.... read about Tasmoto command in there
documentation...

/*
**************************************************************************************
Xsns127Cmnd:

format: Sensor125 1,2,3

0 0 set defaults to file system, reset driver
1 type 0 pulse per unit (GPM....)
1 K-Offset flowrate = (freq + offset) * K --> freq = (PPM / K)
2 K-Offset flowrate = (freq + offset) / K --> freq = (PPM * K)

2 rate_factor // unit per pulse from flow meter examples, float
0.1 0.1 gal per minute GPM
1 1 gal per minute GPM
10 10 gal per minute GPM
100 100 gal gal per minute GPM
7.48052 1 cubic feet Cft
74.8052 10 cubic feet Ctf
748.052 100 cubic feet Cft
1 1 cubic meter M3
1 1 litres LM
3 K // K value from device, float
4 Offset // Offset value from device, float
5 Flow_units
0 = GPM GAL Gallons per minutes
1 = Cft CF Cubic Feet per minutes
2 = M3 CM Cubic Metre per minutes
3 = LM L Litres per minutes
6 Excess Flow Threshold // flow rate at which to trigger an excess flow
7 Excess Flow Threshold Time // time in seconds to report excessive flow
8 Current Send Interval in second's // how often we send MQTT information
when we have a flow
9 MQTT Bit Mask, 16 bits // use to enable/disable MQTT messages
10 Max Flow Rate // Max flow rate for this sensor
11 Debounce 0 = off, 1 = on
12 Debounce Low Time in MS
13 Debounce High Time in MS

**************************************************************************************
MQTT_send_bit_mask: // we use this mask to enable/disable MQTT messages
0 FlowCount
1 Flow
2 FlowPeriod
3 1hrVolume, last hour
-
4 24hrVolume, last 24 hr's
5 RateFactor
6 K
7 OffSet
-
8 FlowUnits
9 VolumeUnits
10 Current1hrVolume
11 Current24hrVolume
-
12 Excess flow flag
13 VolumePerFlow
14
15 Message's
*/

/*
**************************************************************************************
*/
// --------------------> Flow Sensor Defaults (X125)
<-------------------------------

// define here or in --> user_config_override.h
/*
#define xFlowCtr_type 1 // Current type of flow sensor, 0 = flow per unit,
1,2 = K-Offset
#define xFlowCtr_units 0 // Current flow units
#define xFlowCtr_debounce_low 0 // Current debounce values...
#define xFlowCtr_debounce_high 0
#define xFlowCtr_debounce 0
#define xFlowCtr_MQTT_bit_mask 0xffff // MQTT Bit Mask, Controls what we
send via MQTT
#define xFlowCtr_current_send_interval 10 // In second's
#define xFlow_threshold_reset_time (20 * 60 * 1000) // Excessive flow
threshold timeout, in miliseconds (20 Min)
#define xFlowCtr_max_flow_rate 60.0f // Sensor Max Flow rate in units of
flow...
#define xFlowCtr_threshold_max 20.0f // Excessive flow threshold in units
of flow
#define xFlowCtr_rate_factor 1.0f // Current Rate Factor
#define xFlowCtr_k .153f // For K-Offset flow sensor (--> CST 1in ELF
sensor)
#define xFlowCtr_offset 1.047f // Current Offset
*/



~~ _/) ~~~~ _/) ~~~~ _/) ~~~~ _/) ~~

Tom Lafleur

**Comment by malinduta** [comment]
Uploaded the new file. Still no readings.
I am a bit lost...
I have [this](https://www.aliexpress.com/item/1005006053200665.html) sensor.
Specification: Stream pulse characteristics: F=(8*Q-4)±5%, F is the frequency Q is L/Min, that is, 476 pulses per liter of water.
Can the sensor be used with your code?

**Comment by trlafleur** [comment]
The sensor you using is a Hall Effect sensor, the red wire needs to connect
to 5V, black to GND, yellow wire produces a 5V signal, ESP32 is a 3.3v
device,
so, you will need to reduce the voltage with a simple resistor divider..
about 470ohm to the sensor and other ends to input on ESP32, then about 1k
from ESP32 pin to GND....  The sensor Hall Effect may work at 3.3v, then
the divider is not needed, but untested....

Make sure you have not damaged the ESP32 GPIO pin, do the test below

Before you start, connect a push button to ESP32 input pin and GND, press
the button, and see if the Flow sensor LED toggles, to make sure all is
good...
you can omit the heartbeat, and connect the flow LED to GPIO 13, which in
my case is connected to an LED on the ESP32 Feather board..
Results will also show up on Tasmota's main web page...

for my test, I used an Adafruit ESP32 Feather board....
https://www.adafruit.com/product/3405

https://maker.pro/arduino/tutorial/how-to-interface-arduino-with-flow-rate-sensor-to-measure-liquid

~~ _/) ~~~~ _/) ~~~~ _/) ~~~~ _/) ~~

Tom Lafleur

**Comment by trlafleur** [comment]
https://digizone.com.ve/wp-content/uploads/2021/06/yf-b10.pdf

~~ _/) ~~~~ _/) ~~~~ _/) ~~~~ _/) ~~

Tom Lafleur

**Comment by trlafleur** [comment]
https://github.com/bway-dev/flow-sensor-esp32

~~ _/) ~~~~ _/) ~~~~ _/) ~~~~ _/) ~~

Tom Lafleur

**Comment by trlafleur** [comment]
In some reading about the sensor you have it appears to be a very nonlinear
device over its flow range. You may have to figure out an external code,
how to calibrate that or calculate a reasonable K offset factor.

**Comment by malinduta** [comment]
> Make sure you have not damaged the ESP32 GPIO pin, do the test below

The GPIO seems is not damaged. It counts pulses if set as counter, but no led when connected to ground.

**Comment by malinduta** [comment]
Thank you for the infos (links).

Is there a way to adapt the formula F = 6.5163 x Q - 2.7 for my use case?

**Comment by trlafleur** [comment]
Connect a resister about 1.5k to, (in my case) GPIO32. To anode of led,
cathode to gnd.  Should blink on each pulse.  Or use a scope or volt meter

**Comment by trlafleur** [comment]
Read ESP32 arduino program code examples l sent you on how to convert pulse
to volume

You You may want to get that program running first before You tackle
Tasmota

**Comment by malinduta** [comment]
Unfortunately things are nor working (as expected).
I pause/quit the project for the moment, as is taking a lot of time.

Hope I will make it work sometime.
Thank you for your time and for helping me!

**Comment by Noschvie** [comment]
Are your problems hardware or software related?

**Comment by trlafleur** [comment]
I found a flow sensor like yours, connected to my ESP32, with an LED on
gpio 32, the sensor on gpio14

ALL WORKED WELL, ONE JUST NEEDS TO FIND THE CORRECT VALUE TO SCALE PULESES
TO UNIT OF FLOW...

~~ _/) ~~~~ _/) ~~~~ _/) ~~~~ _/) ~~

Tom Lafleur



---------- Forwarded message ---------
From: Tom Lafleur ***@***.***>
Date: Mon, Dec 11, 2023 at 10:24 AM
Subject:
To: Tom Lafleur ***@***.***>

**Comment by trlafleur** [comment]
![IMG_2335](https://github.com/trlafleur/Flow-Sensor-Tasmota/assets/4571691/7eb1fb2c-da51-4305-a495-a1270412cffc)

**Comment by trlafleur** [comment]
here is a photo of my test

**Comment by malinduta** [comment]
> Are your problems hardware or software related?

~~Software, as I tested with 2 boards.~~
User related :(

**Comment by trlafleur** [comment]
please see my current post on web site...



~~ _/) ~~~~ _/) ~~~~ _/) ~~~~ _/) ~~

Tom Lafleur

**Comment by trlafleur** [comment]
github site

~~ _/) ~~~~ _/) ~~~~ _/) ~~~~ _/) ~~

Tom Lafleur

**Comment by malinduta** [comment]
> I found a flow sensor like yours, connected to my ESP32, with an LED on gpio 32, the sensor on gpio14

Those pins are not available for me, as I only have ESP32 D1 Mini.
Used gpio 16 for flow sensor and gpio 2 for led (built in).

> ALL WORKED WELL, ONE JUST NEEDS TO FIND THE CORRECT VALUE TO SCALE PULESES TO UNIT OF FLOW...

How to do that? My sensor outputs 476 pulses per liter of water.

**Comment by trlafleur** [comment]
Change them in Tasmota config!! It’s easy.

**Comment by trlafleur** [comment]
Set rate_factor (flow factor) in the command line  Sensor125 2,0.00210084
should work, it only displays as 2 digits 0.00
rate_factor can be any +- floatpoint number when you get it working, adjust
this parameter to whatever you want!

each pulse is 1/476 = 0.0021008403 liter
it's all easy math!

~~ _/) ~~~~ _/) ~~~~ _/) ~~~~ _/) ~~

Tom Lafleur

**Comment by malinduta** [comment]
Do not know what to say...
Tryed multiple gpio on 2 boards. Nothing gets counted on web interface, no led is on.

**Comment by trlafleur** [comment]
did you make any changes to tasmota config..... and move the H2O flow to
the correct pin??

[image: image.png]


~~ _/) ~~~~ _/) ~~~~ _/) ~~~~ _/) ~~

Tom Lafleur

**Comment by trlafleur** [comment]
try making change it
*Template *


~~ _/) ~~~~ _/) ~~~~ _/) ~~~~ _/) ~~

Tom Lafleur

**Comment by malinduta** [comment]
> did you make any changes to tasmota config..... and move the H2O flow to the correct pin?? [image: image.png]

Yes, sure.

**Comment by trlafleur** [comment]
what pins are you using on your board???    I got a D1 mini, connected to
GPIO16, and changed the template to GPIO16, saved it
works just fine...

2 screenshots and a photo of the setup...



[image: image.png]

[image: image.png]




~~ _/) ~~~~ _/) ~~~~ _/) ~~~~ _/) ~~

Tom Lafleur

**Comment by malinduta** [comment]
> 2 screenshots and a photo of the setup...
[image: image.png]
[image: image.png]

The images are not shown...

**Comment by trlafleur** [comment]
send me you direct email address
tom@lafleur.us

**Comment by malinduta** [comment]
Sent you a email.

**Comment by malinduta** [comment]
> Are your problems hardware or software related?

Sadly, user related problems.

**Comment by trlafleur** [comment]
New image on GitHub now showing 4 decimal places for Flo rate factor

**Comment by malinduta** [comment]
It`s working! :)
![Working](https://github.com/trlafleur/Flow-Sensor-Tasmota/assets/45850545/cf2642c7-c644-4d11-9d7f-9d96ff59cf1f)

**Comment by Noschvie** [comment]
Great news! Are you able, willing to upgrade to latest Tasmota?

**Comment by trlafleur** [comment]
My development environment has been 12.3.x for Awhile, stable , no issues…..
Yesterday, I downloaded 13.2.0, and 13.3.0.1, compiled un modified code for
a basic ESP32, no issues, but binary when loaded into a device gives
startup boot error at run time on multiple devices. Pre made binary’s from
web site work fine.

Development is with VS code…

Unclear what the issues are, no time to investigate this week, something is
out of sync
